# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1b16a1e6e2d45d711e98261b17eb987aedf80a27c0b6d4a6b0b1bdbb02daa842460d3702ac8603d052f526213926e275b4e59eea518e8ebd97ac4b8a0327edf

test:
  secret_key_base: d55b6b94bb73ad9f7c02a32afd94e3b1f86aac1d7a9692f3d4c4926b8ac5f105521082f5cb2c989004f785d71abd03047b65042690b7321a4e43ebe3d30155e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
